name: Test

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  ARCH_TYPE: sm_70

jobs:
  test-golang-linux:
    name: Test Golang on Linux
    runs-on: [self-hosted, Linux, X64, icicle]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Build CUDA libs
      run: |
        git clone https://github.com/username/another-repo.git
        cd another-repo/goicicle
        make all
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/goicicle" >> $GITHUB_ENV
    - name: Run Golang Tests
      run: |
        go test ./bn254 ./bls12377 -count=1
